In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
dataset =  pd.read_csv("bill_authentication.csv")
#Data were extracted from images that were taken from genuine and forged banknote-like specimens. For digitization,
#an industrial camera usually used for print inspection was used. The final images have 400x 400 pixels. 
#Due to the object lens and distance to the investigated object gray-scale pictures
#with a resolution of about 660 dpi were gained. Wavelet Transform tool were used to extract features from images.

In [8]:
dataset.head(1000)  # we would like to perform a classification according to the variance, skewness, curtosis and entropy
# we will determine if the banknote can be authenticated or not!


Variance  Skewness   Curtosis   Entropy  Class
0     3.62160   8.66610  -2.807300 -0.446990      0
1     4.54590   8.16740  -2.458600 -1.462100      0
2     3.86600  -2.63830   1.924200  0.106450      0
3     3.45660   9.52280  -4.011200 -3.594400      0
4     0.32924  -4.45520   4.571800 -0.988800      0
5     4.36840   9.67180  -3.960600 -3.162500      0
6     3.59120   3.01290   0.728880  0.564210      0
7     2.09220  -6.81000   8.463600 -0.602160      0
8     3.20320   5.75880  -0.753450 -0.612510      0
9     1.53560   9.17720  -2.271800 -0.735350      0
10    1.22470   8.77790  -2.213500 -0.806470      0
11    3.98990  -2.70660   2.394600  0.862910      0
12    1.89930   7.66250   0.153940 -3.110800      0
13   -1.57680  10.84300   2.546200 -2.936200      0
14    3.40400   8.72610  -2.991500 -0.572420      0
15    4.67650  -3.38950   3.489600  1.477100      0
16    2.67190   3.06460   0.371580  0.586190      0
17    0.80355   2.84730   4.343900  0.601700      0
18    1.44790  -4.87940   8.342800 -2.108600      0
19    5.24230  11.02720        NaN -4.101300      0
20    5.78670   7.89020  -2.619600 -0.487080      0
21    0.32920  -4.45520   4.571800 -0.988800      0
22    3.93620  10.16220  -3.823500 -4.017200      0
23    0.93584   8.88550  -1.683100 -1.659900      0
24    4.43380   9.88700  -4.679500 -3.748300      0
25    0.70570  -5.49810   8.336800 -2.871500      0
26    1.14320  -3.74130   5.577700 -0.635780      0
27   -0.38214   8.39090   2.162400 -3.740500      0
28    6.56330   9.81870  -4.411300 -3.225800      0
29    4.89060  -3.35840   3.420200  1.090500      0
..        ...       ...        ...       ...    ...
970  -2.32990  -9.95320   8.475600 -1.873300      1
971   0.00312  -4.00610   1.795600  0.917220      1
972   1.35180   1.05950  -2.343700  0.399980      1
973   1.23090   3.89230  -4.827700 -4.006900      1
974  -5.03010   7.50320  -0.133960 -7.503400      1
975  -3.07990   0.60836   2.703900 -0.237510      1
976  -2.29870  -5.22700   5.630000  0.917220      1
977  -1.23900  -6.54100   4.815100 -0.033204      1
978   0.75896   0.29176  -1.650600  0.838340      1
979   1.67990   4.20680  -4.539800 -2.393100      1
980   0.63655   5.20220  -5.215900 -6.121100      1
981  -6.05980   9.29520  -0.436420 -6.369400      1
982  -3.51800   2.87630   0.154800 -1.208600      1
983  -2.03360  -1.40920   1.158200  0.365070      1
984  -0.69745  -1.76720  -0.344740 -0.123720      1
985   0.75108   1.91610  -3.109800 -0.205180      1
986   0.84546   3.48260  -3.630700 -1.396100      1
987  -0.55648   3.21360  -3.308500 -2.796500      1
988  -3.68170   3.22390  -0.693470 -3.400400      1
989  -6.75260   8.81720  -0.061983 -3.725000      1
990  -4.57700   3.45150   0.667190 -0.947420      1
991  -2.98830   0.31245   0.450410  0.068951      1
992  -1.47810   0.14277  -1.162200 -0.485790      1
993  -0.46651   2.33830  -2.981200 -1.043100      1
994  -0.87340   1.65330  -2.196400 -0.780610      1
995  -2.12340   1.18150  -0.555520 -0.811650      1
996  -2.31420   2.08380  -0.468130 -1.676700      1
997  -1.42330  -0.98912   2.358600  0.394810      1
998  -3.08660  -6.63620  10.540500 -0.891820      1
999  -4.73310  -6.17890  11.388000 -1.074100      1

[1000 rows x 5 columns]

In [9]:
dataset.shape

(1372, 5)

In [10]:
# Number of missing values in each column of training data
missing_val_count_by_column = (dataset.isnull().sum())
print(missing_val_count_by_column[missing_val_count_by_column > 0])  

Variance    1
Skewness    6
Curtosis    8
Entropy     4
dtype: int64


In [11]:
from sklearn.impute import SimpleImputer  # Imputer is for missing values

# Fill in the lines below: imputation
my_imputer = SimpleImputer()
datasetClean = pd.DataFrame(my_imputer.fit_transform(dataset))
# Fill in the lines below: imputation removed column names; put them back
datasetClean.columns = dataset.columns
# In general you can use this imputer without worrying about the missing values.

In [12]:
# Number of missing values in each column of training data
missing_val_count_by_column = (datasetClean.isnull().sum())
print(missing_val_count_by_column[missing_val_count_by_column > 0]) 

Series([], dtype: int64)


In [13]:
cor = datasetClean.corr()   # correlation calculation, we are trying to eliminate non-relevant columns from the dataset!
cor_target = abs(cor["Class"])
#Selecting highly correlated features
relevant_features = cor_target[cor_target>0.0001]  # change the parameter, to see if you can get more 
#columns related to "AveragePrice" . In our case "type" columns looks not relevant therefore we are going to drop it!
relevant_features.index
# but what if we dont drop? we cannot guarantee that high correlation means good results!

Index(['Variance', 'Skewness', 'Curtosis', 'Entropy', 'Class'], dtype='object')

In [9]:
#datasetClean.drop('Entropy', axis=1, inplace=True)  #### according to the result of correlation we will drop this column. 
# What if it has still effect on the result despite of the correlation?
#Examine the training with and without this "type" column!

In [10]:
X = datasetClean.drop('Class', axis=1)
y = datasetClean['Class']

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [12]:
from sklearn.svm import SVC  # support vector machine - linear
svclassifier = SVC(kernel='linear')
fitted = svclassifier.fit(X_train, y_train)

In [13]:
y_pred = svclassifier.predict(X_test)

In [14]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[148   4]
 [  0 123]]
              precision    recall  f1-score   support

         0.0       1.00      0.97      0.99       152
         1.0       0.97      1.00      0.98       123

    accuracy                           0.99       275
   macro avg       0.98      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275



In [15]:
from sklearn.metrics import accuracy_score
print('SVC:',accuracy_score(y_test, y_pred)*100,'%')

SVC: 98.54545454545455 %


In [16]:
# Try to predict the price, you can choose any row from data set and check if the prediction "0" or "1" is correct!
test =datasetClean.loc[[1000]]   # take Nth row to check your prediction result manually 
test = test.drop('Class', axis=1)  # drop target "class" column
prediction= fitted.predict(test)
prediction

array([1.])

In [17]:
#now here is your new perspective, you cant always rely on numbers yea?
# here is how you can really predict your ML algorithm. you show it a NEW data and it gives you a result!
#dont forget about this part of code, you will need to check your final predictions in your career(dont worry about exam)

data = [[1.364,2.1539,2.457,2.99532]]   # you can also create a dataframe by yourself and feed it into SVM prediction
# imagine you have a banknote which has values as above. See if it can pass the authentication or not
# 1 for the pass. 0 for not-pass
  
# Create the pandas DataFrame 
df = pd.DataFrame(data, columns = ['Variance', 'Skewness','Curtosis','Entropy']) 
df

Variance  Skewness  Curtosis  Entropy
0     1.364    2.1539     2.457  2.99532

In [18]:
prediction= fitted.predict(df)  # you can adjust the values and see what will your model generate.
# this is a binary classification so result will be either 1 or 0 as yes or no.
prediction

array([0.])